### ISSUE TITLE
子组件写法

### ISSUE THREAD

**Issue by yueduz** [vifird/react-keeper#10]
能不能支持这种写法
```
 <Route index cache>
                      <List store=AppStore/>
</Route>
```
这样写传参数很麻烦啊
`  <Route component={Content} path="/content" />`

**Comment by vifird** [comment]
@yueduz 这是一个很好的写法，我们会尽快支持。

**Comment by vifird** [comment]
@yueduz Keeper现在已经支持这种写法了，使用npm重新安装一下即可，这种写法也同样支持cache、index、miss标签。

**Comment by yueduz** [comment]
`ERROR in ./~/react-keeper/BrowserRouter.js
Module not found: Error: Can't resolve './Util' in '/home/lei/www/ayahuo/node_modules/react-keeper'
 @ ./~/react-keeper/BrowserRouter.js 45:12-29
 @ ./~/react-keeper/index.js
 @ ./blog/components/Main/index.js
 @ ./blog/root.js
 @ ./blog/index.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?path=/__what&timeout=2000&overlay=false ./index.js

`

**Comment by vifird** [comment]
@yueduz 能提供下代码信息吗？

**Comment by yueduz** [comment]
![2017-04-28 13-36-46](https://cloud.githubusercontent.com/assets/1448159/25515535/cf2aaae2-2baa-11e7-82df-566010738472.png)

**Comment by yueduz** [comment]
只要导入 import { HashRouter, Route } from 'react-keeper' 就报错，是不是package.js没写对

**Comment by yueduz** [comment]
![2017-04-28 22-42-14](https://cloud.githubusercontent.com/assets/1448159/25533687/0fbfcd66-2bf7-11e7-94d3-c869897a1aaa.png)
文件名大小写错了

**Comment by vifird** [comment]
@yueduz 好的，如果问题还存在，重新安装一下即可。

**Comment by yueduz** [comment]
这种写法不需要.
