### ISSUE TITLE
用a标签替代Link和CacheLink时，无法跳转

### ISSUE THREAD

**Issue by MeiJunNa** [vifird/react-keeper#104]
`<HashRouter>
                <div>
                    <ul className='nav navbar-nav'>
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href='/about'>About</a>
                        </li>
                    </ul>
                    <hr />
                    <Route cache component={Home} path='/' />
                    <Route cache path='/about' component={About} />
                </div>
            </HashRouter>`
首页刷新进入时：http://localhost:3000/#/，当页面跳转时，链接为http://localhost:3000/about#/

**Comment by vifird** [comment]
@MeiJunNa 使用a代替link时，href需要填写完整的路径，比如`<a href='#/about'>`
