### ISSUE TITLE
Control.path 得不到当前路径

### ISSUE THREAD

**Issue by yueduz** [vifird/react-keeper#11]
![2017-05-01 23-12-29](https://cloud.githubusercontent.com/assets/1448159/25583335/f7fd11fe-2e56-11e7-910e-f3bef9e11558.png)

```
<Route enterFilter={ AppState.setContent } controlPath={Control.path} path="/content/">
  <Content source={AppState.content} />
</Route>
```
```
  setContent(callback, props) {
    console.log(callback);
    console.log(props);
    axios.get("/api/content/123")
      .then((res) => {
        this.content = res.data;
        // console.log(res.data);
      })
      .catch((error) => console.log(error))
  }
```

**Comment by vifird** [comment]
@yueduz Yeah, it's normal performance. Route is always mounted ( while it's parent is mounted), so it's props‘ value will not change, even it's component'(the component defined on the Route's property) mount status changed.
But we could give a object value ,not a string(or number), to let it react on the change. Such as:
```
<Route enterFilter={ AppState.setContent } controlPath={Control} path="/content/">
  <Content source={AppState.content} />
</Route>
setContent(callback, props) {
    console.log(props.controlPath.path);
  }
```
