### ISSUE TITLE
Route配置的时候的 loadComponent

### ISSUE THREAD

**Issue by Lori-Yez** [vifird/react-keeper#12]
你好，按照文档写的情况loadComponent 用了 System.import 是有引入外部的 Systemjs还是什么情况呢？package.json，没看到相关的信息。

注：我的 node 版本是7.9

**Comment by vifird** [comment]
@Lori-Yez  System.import是systemjs的语法，如果使用需要引入systemjs，也可以使用其他AMD规范的模块化工具，比如requirejs.

**Comment by Lori-Yez** [comment]
最后是这么解决的
`<Route path="/details" loadComponent={(cb) => {
                    require.ensure([], (require) => {
                        cb(require('../Component/details/details.jsx').default)
                    }, 'Details')
                }
            }`

**Comment by vifird** [comment]
@Lori-Yez 这样也是可以的，这是webpack自带的AMD实现。
