### ISSUE TITLE
Link 没有<a>的黙以样式

### ISSUE THREAD

**Issue by yueduz** [vifird/react-keeper#13]
鼠标指上去不会变成手指

**Comment by vifird** [comment]
@yueduz 
这个可能是受其他库的影响，Link默认会渲染成<a>，然后其他的交由浏览器来解析。

**Comment by yueduz** [comment]
@vifird 我认为是渲染出来的<a>元素没有href属性的原因,没有href属性黙认是不会变成手指的

**Comment by vifird** [comment]
@yueduz 这是确实是Link组件的影响，Link在渲染时去掉了href属性。这个问题现在可以临时用CSS解决，后面我们会在下一个小版本解决这个问题。

**Comment by yueduz** [comment]
@vifird 我安装了新版后问题没有解决,反而文件名大小写问题又出现了
ERROR in ./~/react-keeper/Util.js
Module build failed: Error: ENOENT: no such file or directory, open '/

/RouteControl.js

**Comment by vifird** [comment]
@yueduz 重新安装一下最新版，这两个问题解决了。对于<Link>编译生产的<a>，自动加上了`href="javascript:void(0)"`。

**Comment by yueduz** [comment]
在外面暂时试不了，我什么不直接写上真实的地址，然后阻止黙认事件。既然都已经监听了click事件。

vifird <notifications@github.com>于2017年5月27日周六 14:14写道：

**Comment by vifird** [comment]
@yueduz 这两种方案都可以实现，对比起来，事件监听更适合当前的场景，比如CacheLink内部集成缓存代理的实现。

**Comment by scriptdw** [comment]
@vifird 你好,`<Link>`编译出来的`<a>`标签,自动加上了`href="javascript:void(0)"`.现在点击链接跳转不了,请问该怎么跳转?`to`属性是被抛弃了吗?

**Comment by vifird** [comment]
@scriptdw to属性不会被抛弃的。页面跳转都是使用的事件形式，看是不是有其他事件影响到<a>的跳转。

**Comment by scriptdw** [comment]
@vifird 好的,谢啦*^_^*
