### ISSUE TITLE
Props-Type warning with react 15.4.2

### ISSUE THREAD

**Issue by catouse** [vifird/react-keeper#14]
![image](https://cloud.githubusercontent.com/assets/472425/26768612/a1e675da-49db-11e7-9092-7281f7826bb1.png)

**Comment by vifird** [comment]
`props-type` has been splited from the main `react` pack and will be removed since react 16.x, we will update our base code in next version. Now, this can still work on react 15.x and 0.14.

**Comment by vifird** [comment]
@catouse We had repaired this problem. Run install again.
