### ISSUE TITLE
clone项目后，无法正常运行example

### ISSUE THREAD

**Issue by inier** [vifird/react-keeper#16]
1. npm安装时， 提示"react-router": "next"异常
![image](https://user-images.githubusercontent.com/7600897/27569682-6db71ede-5b2b-11e7-89c0-dd8a2e3a7bed.png)

2. 更换react-router版本为4.1.1后，运行报错
![image](https://user-images.githubusercontent.com/7600897/27569707-9682a572-5b2b-11e7-9e49-d29c0e9e91a0.png)

**Comment by vifird** [comment]
Pull the repository again. 
React-Router is used in example project, is has removed the 'next' version. We have repaired it.
