### ISSUE TITLE
如何不把页面记录history？

### ISSUE THREAD

**Issue by BLSM53** [vifird/react-keeper#18]
请问如果我有一个搜索的过渡页不想把它记录到history中，比如页面1->页面2->页面3，我想在页面3返回时直接到页面1(不确定页面)，不经过页面2，现在有这样的功能么？如果有应该如何做呢？谢谢

**Comment by itxuye** [comment]
页面2跳到3的时候使用replace  @BLSM53

**Comment by BLSM53** [comment]
@itxuye 完美解决，谢谢
