### ISSUE TITLE
在routers文件替换为keeper后, {this.props.children}不起作用了.

### ISSUE THREAD

**Issue by ghost** [vifird/react-keeper#2]
## routers.js: 
```
<Route component={ PageHome } path="/" >
            <Route component={PageZuzhi} path="zuzhi" />
            <Route component={PageJiceng} path="jiceng" />
        </Route>
```
## PageHome 组件: 
```
<div className="container" id="container">
     {this.props.children}
     <Menu menu={menu} selectedTab={selectedTab} onChange={handleChange} />     
 </div>
```
问题: 不支持this.props.children 调用吗?

**Comment by vifird** [comment]
React-Keeper是支持 this.props.children 的调用的，程序的示例也有这部分代码，可以参考文件：`/example/main/pages/products/Products.js` 。

**Comment by xttianma** [comment]
## 1. 里面导入的不是keeper ,是 react-flex-router? 
## 2. 问题依然存在: 

> 用子路由的写法, 其内的路由组件是null
```
<Route component={ PageHome } path="/" >
        <Route component={PageZuzhi} path="zuzhi" />
        <Route component={PageJiceng} path="jiceng" />
</Route>
```
![image](https://cloud.githubusercontent.com/assets/22427990/23012840/15a418b6-f463-11e6-9328-2af1885a8a52.png)


---
> 不用子路由,就可以访问
```
<Route component={ PageHome } path="/" />
<Route component={PageZuzhi} path="zuzhi" />
<Route component={PageJiceng} path="jiceng" />
```

**Comment by xttianma** [comment]
问题是在routers.js文件?

---
>完整的js
```
import ReactDOM from 'react-dom';
import { HashRouter, Route } from 'react-keeper'

import PageHome from 'pages/home/';
import PageZuzhi from 'pages/zuzhi/';
import PageJiceng from 'pages/jiceng/';

import PageOrgBase from 'pages/org_base/';

const rootRoute = <HashRouter>
    <div>
        <Route component={ PageHome } path="/" >
            <Route index component={PageZuzhi} />
            <Route component={PageZuzhi} path="/zuzhi" />
            <Route component={PageJiceng} path="/jiceng" />
        </Route>
        <Route path="/org/base" component={PageOrgBase}/>
    </div>
</HashRouter>

ReactDOM.render( rootRoute, document.getElementById('App'));
```

**Comment by vifird** [comment]
1.  React-Flex-Router是曾经使用过的名字，在正式开源之前更名为了‘React-Keeper’
2. 可以确定的是 this.props.children已经生效了(内部的3个Route组件已经被包含)，现在考虑可能是由于地址不匹配导致的内部Route未渲染，可以这样测试一下，在其中一个Route里加入`miss`属性(在同级Route不匹配时渲染)，比如：`<Route miss component={PageJiceng} path="/jiceng" />`

**Comment by xttianma** [comment]
ok, 加入miss 有效果.
包含的子路由规则里面,那条有miss 属性,那条就显示了.

**Comment by xttianma** [comment]
我用脚手架重新创建了一个项目
> 环境:
1. win10
2. node : 6.9.5
3. 前端构建: nowa 
3. 脚手架: salt  

这个脚手架的demo,就是一个典型的包含子路由的app.js (内置了React对象)

```
import { HashRouter, Route } from 'react-keeper'

const PageHome = require('../pages/home');
const PageDemo = require('../pages/demo');

class App extends React.Component {
    render() {
        return (
            <div> {this.props.children} </div>
        );
    }
}

ReactDOM.render(
    <HashRouter><div>
        <Route name="app" path="/" component={App}>
            <Route index component={PageHome}/>
            <Route  path="home" component={PageHome}/>
            <Route  path="demo" component={PageDemo}/>
        </Route>
    </div></HashRouter>,
    document.getElementById('App')
);
```

**Comment by vifird** [comment]
@xttianma 可否提供一份完整的代码示例？我们可以安排专人进行测试。

**Comment by xttianma** [comment]
可以,我怎么发送给您?

**Comment by vifird** [comment]
@xttianma 发到这个邮箱：vifirde@gmail.com

**Comment by xttianma** [comment]
[nowakeeper.zip](https://github.com/vifird/react-keeper/files/779520/nowakeeper.zip)

使用方法: (nowa参考:　https://nowa-webpack.github.io/docs/　)
1. 安装nowa: 
```
npm i nowa -g --registry=https://registry.npm.taobao.org && nowa install --registry=https://registry.npm.taobao.org
```
2. 进入代码目录,安装依赖:　npm install
3. 运行项目: nowa server

**Comment by vifird** [comment]
@xttianma 好的。

**Comment by xttianma** [comment]
有什么发现吗?

**Comment by vifird** [comment]
@xttianma 工程师正在处理

**Comment by vifird** [comment]
@xttianma 已经找到问题，我们对匹配算法做了一点优化，现在可以了，再执行一下`npm install react-keeper`进行下更新即可。
BTW，尽量使用`Link`和`CacheLink`组件进行页面的跳转处理，以便于以后项目维护时对不同Router(Hash、Browser、Memory)的自由切换。

**Comment by xttianma** [comment]
我这里是在移动端 ( 钉钉+node+react ) 使用:　Link和CacheLink我感觉当前用的机会不多．　
因为大部分交互操作，都在响应事件里面完成的．

用子组件的这个用法是特殊场景:
tabbar的用法. tabbar里面包含的不是静态的view, 而是路由的path对应的组件对象. 
---
 改用keeper后, 少不了麻烦你们, 由于reac-reouter中文教程还是老版本的多, 我以及国内react初学者
对路由的学习和使用是个门槛. 希望keeper能在文档上丰富些. 不光可以帮助router熟悉的用户,也能帮助react的初学者.

**Comment by vifird** [comment]
@xttianma 文档我们还在积极准备，中文文档也会在近期推出。

**Comment by FX00** [comment]
`<Route name="app" path="/" component={ App } enterFilter={LoginFilter}>
        <Route index component={Home} path= '/home' miss/>
        <Objectset.route />
        <Route loadComponent={Addobject}  path= '/addobject'>
          <Route component={Taglist} path="/taglist" /> 
        </Route>
    </Route>`
请问下，类似这样taglist跳转地址该怎么写，匹配不到，其他都能正常

**Comment by FX00** [comment]
`
<Route name="app" path="/" component={ App } enterFilter={LoginFilter}>
        <Route index component={Home} path= '/home' miss/>
        <Objectset.route />
        <Route loadComponent={Addobject}  path= '/addobject'>
          <Route component={Taglist} path="/taglist" /> 
        </Route>
    </Route>
`
请问下这样taglist的跳转地址该怎样写，匹配不到，其他都正常，在home上加了miss就<Link to='./taglist'></Link>跳转到home

**Comment by vifird** [comment]
这样写：`<Link to='/addobject/taglist'></Link>`
