### ISSUE TITLE
clear cache page

### ISSUE THREAD

**Issue by 17x** [vifird/react-keeper#20]
How to programmably clear a cached page . 
May like this : 

// after login
`
reactKeeper.clearCache('index.home.tab1')
`

**Comment by vifird** [comment]
Do like this to clear a cached page in next version: 
[ This is not supported now, we are doing on this. ]
```
class A extends Component {
  render() {
    return (
      <div>
        <Route cache={this.state.cache} component={ Home } path='/' />
        <button onClick={ e=>{ this.setState({ cache: false }) } }>clearCache</button>
      </div>
    )
  }
}
```

**Comment by vifird** [comment]
@17x Now Keeper has support clearing pages' cache. See [V2.1](https://github.com/vifird/react-keeper/blob/master/docs/Version.md).

**Comment by 17x** [comment]
Thanks your great work ! 
And look forward next version for save scroll-bar position .
