### ISSUE TITLE
replace跳转页面如何获取state

### ISSUE THREAD

**Issue by BLSM53** [vifird/react-keeper#27]
使用replace跳转页面，但是在跳转后的页面无法获取到state的值，this.controlState为空，请指教如何获取state值呢？

**Comment by vifird** [comment]
@BLSM53 是使用的history.replace还是Control.replace？

**Comment by BLSM53** [comment]
@vifird Control.replace

**Comment by vifird** [comment]
问题已经修复，重新安装下keeper即可。

**Comment by BLSM53** [comment]
谢谢！
