### ISSUE TITLE
链接跳转后的页面缓存问题

### ISSUE THREAD

**Issue by BLSM53** [vifird/react-keeper#29]
HI，现在在2.0.6和2.0.7版本遇到的一个问题是，通过一个链接传不同的参数跳转到一个页面，比如这样的方式：Control.go('/a', {id: 1})或<Link to"/a/1">，这样的方式，路由配置为<Route path="/a/:id">

但是现在发现，但是现在通过以下步骤跳转页面：首页--><Link to"/a/1">-->首页--><Link to"/a/2">
发现并未走到2页面，依然还是跳转到1页面，请问有没有遇到这样问题的同学？怎么解决的呢？

**Comment by vifird** [comment]
@BLSM53 页面初始化的处理你应该是写在componentDidMount函数里了。这种情况发生的原因是由于两个页面使用的是同一个组件，路由切换时页面并没有解绑，复用的之前的组件。有两种方式可以解决这个问题：
1. 为对应的Route组件添加key，key可为页面的id。原理：保证两个页面的key不同，这样在切换时，两个页面会被认为是两个组件，旧组件解绑，新组件重新创建，会重新调用新组件的componentDidMount。
2. 在页面组件componentWillReceiveProps（或componentDidUpdate）里写添加处理，内容与componentDidMount相同。原理：组件未解绑，但是props有变化。
