### ISSUE TITLE
cache 与 react-iscroll 有冲突

### ISSUE THREAD

**Issue by Chryseis** [vifird/react-keeper#33]
当我给用react-iscroll包的组件上加cache后，切换路由后就无法滚动，必须改变下组件内的state的才能滚动，cache的原理是什么？不过当我用原生的iscroll就没有产生这个问题。
![image](https://user-images.githubusercontent.com/13757352/31487952-c3c7b4d6-af6e-11e7-9892-bfcc274832f6.png)
seller组件和ratings组件用了react-iscroll包的，goods用的是原生的。
代码地址：https://github.com/Chryseis/elemDemo4React

**Comment by vifird** [comment]
@Chryseis cache切换的过程是对页面的隐藏，隐藏方式使用的display:none来实现。现在考虑可能是react-iscroll在页面不可见时对事件解除了绑定，可以先不接cache，直接手动控制页面的可见状态测试一下结果。

**Comment by Chryseis** [comment]
@vifird 谢谢，我试下
