### ISSUE TITLE
关于cache页面渲染的问题

### ISSUE THREAD

**Issue by BLSM53** [vifird/react-keeper#34]
你好，我在使用keeper的过程中遇到了一个问题，我的首页（Index）路由设置了cache和index属性，但是我发现当我在其他页面时，这个页面经常还会刷新，而且这种刷新只触发render，导致在DOM渲染完成后绑定得效果（比如Swiper插件渲染的效果）都不会重新渲染，从而导致页面显示效果出错，请问这种问题有解决办法么？

**Comment by vifird** [comment]
这个可能是由于全局的数据变化引起的，如果不希望引起重新渲染，可以在shouldComponentUpdate里增加条件判断。
