### ISSUE TITLE
怎么样让/路径不匹配 /home 路径

### ISSUE THREAD

**Issue by BestDingSheng** [vifird/react-keeper#35]
<Route cache miss index path="/" component={Home} />
<Route path="/roster" title={"hello"} component={Roster} />
<Route path="/sub/:num" component={Sub} />
上面这三个路由值显示home这个组件 怎么让 / 只匹配 /

**Comment by vifird** [comment]
'/' 只匹配'/'，可以这样配置: path='/>'。'>'标识以此结尾，类似于正则里的'$'。可以参考文档：https://github.com/vifird/react-keeper/blob/master/docs/RouteMapping.md

**Comment by BestDingSheng** [comment]
@vifird  谢谢  还有2个问题  Control.go   Control 需要引入吗 ,  还有 Link 组件怎么给当前路由加个类名，比如现在路由是 /   <Link to='/' class='active'>

**Comment by BestDingSheng** [comment]
@vifird @vifird 谢谢 还有2个问题 Control.go Control 需要引入吗 , 还有 Link 组件怎么给当前路由加个类名，比如现在路由是 /   给 Link to = '/'  这个组件加个 active 之类的类名

**Comment by vifird** [comment]
Control需要引入，和Link引入方式一样。
Link支持className和activeClassName：`<Link to={ pathname + '/overview' } className='button' activeClassName='active'>Overview</Link>`，可以参考文档：[Link -> activeClassName](https://github.com/vifird/react-keeper/blob/master/docs/Link.md)

**Comment by BestDingSheng** [comment]
谢谢 我好好把文档在看一篇  英文不是很好  麻烦您了

**Comment by vifird** [comment]
好的👌
