### ISSUE TITLE
Control.go(-1)回退的时候能够重新设置state吗？

### ISSUE THREAD

**Issue by jiang263** [vifird/react-keeper#37]

**Comment by vifird** [comment]
这个不会重新设置的，回退时会恢复之前的状态。

**Comment by jiang263** [comment]
如果回退的时候想重新设置状态，有没什么好的思路

**Comment by vifird** [comment]
其实并不建议这样做，因为用户有可能在浏览器点击后退按钮。如果想实现，可以结合`Control.replace`来实现：[Control Docs](https://github.com/vifird/react-keeper/blob/master/docs/Control.md)

**Comment by jiang263** [comment]
@vifird 之前是考虑用Control.replace来做，但是考虑到业务的需求，Control.replace实现不了

**Comment by vifird** [comment]
可否介绍下业务场景？

**Comment by jiang263** [comment]
@vifird 有a，b，c，d，四个页面，从a列表页面调到b页面，再从b页面跳到c页面，之后c再跳到d页面，在d页面点击后退按钮返回b页面，然后返回，回到a页面

**Comment by vifird** [comment]
@jiang263 建议的做法：在Control.go(-n)之后调用Control.replace()进行状态替换。
