### ISSUE TITLE
CacheLink不能缓存我的源页面，怎么回事？？

### ISSUE THREAD

**Issue by jiang263** [vifird/react-keeper#38]

**Comment by vifird** [comment]
可否提供代码供我们测试一下？

**Comment by jiang263** [comment]
<CacheLink to={  rowData.type==0?'':(rowData.type==2?
                            `/evaluationInfo/${rowData.rid}`
                            :`/courseInfo/${rowData.rid}`)}
                               state={{isCompany:0}}
                    >
                        <Item multipleLine>
                            <span>{rowData.send_time}</span> <Brief>{rowData.content}</Brief>
                        </Item>
                        <div className=""/>
                    </CacheLink>
这是列表的item，点进去我的列表页面没有缓存

**Comment by vifird** [comment]
@jiang263 参见：[issues 41](https://github.com/vifird/react-keeper/issues/41)。
