### ISSUE TITLE
如何将缓存的页面给清除

### ISSUE THREAD

**Issue by laden666666** [vifird/react-keeper#4]
在当前页面访问下一页面时候，缓存当前页面；在当前页面执行Control.go(-1)的时候，释放掉当前页面

**Comment by laden666666** [comment]
发现CacheLink就能满足我的需求，但是我希望使用Control来实现我想要的功能，希望能够在Control中提供我渴望的api

**Comment by vifird** [comment]
@laden666666 这个是可以的，CacheLink本身是临时缓存，当页面地址变化不符合缓存条件的时候（比如回退或跳转到新的页面），会自动清空缓存。

**Comment by YDJSZY** [comment]
如果我想在enterFilter里做判断再决定是否清除缓存以便重新渲染该怎么做呢？比如我在b页面里Control.go('/a',{name:"xxx"});然后在a的enterFilter里要判断是否有携带参数，有的话清除缓存，但是这个判断要怎么做？打印props并没有{name:"xxx"}存在。这个state是在哪里取呢？还有清除缓存怎么做？CacheLink具体是怎么用的呢？谢谢！
