### ISSUE TITLE
一个版本问题

### ISSUE THREAD

**Issue by jiang263** [vifird/react-keeper#41]
@vifird 版本2.0.6Cachelink是可以缓存的，Control.replace不能修改state，最新版可以Control.replace并修改state，Cachelink不能缓存，不知道是不是我的代码写错了，我用的是这样

**Comment by vifird** [comment]
Control.replace可以修改state，是新版本的特性。
CacheLink如果不能缓存，这是个问题，我们看一下。

**Comment by vifird** [comment]
CacheLink问题已经修复，请安装最新版Keeper.

**Comment by jiang263** [comment]
@vifird 好的，谢谢
