### ISSUE TITLE
使用动态路由 的一些问题

### ISSUE THREAD

**Issue by itxuye** [vifird/react-keeper#44]
目前安装文档配置动态路由,出现下面的问题
![wechatimg4](https://user-images.githubusercontent.com/9589686/32371652-b38e023a-c05f-11e7-9e46-c4965dab7271.jpeg)
代码:
![wechatimg5](https://user-images.githubusercontent.com/9589686/32371667-c217b698-c05f-11e7-8e3b-5472e2d0c170.jpeg)
![wechatimg6](https://user-images.githubusercontent.com/9589686/32371669-c261adca-c05f-11e7-8347-72a8c7340259.jpeg)
可能是我的使用问题，麻烦提供详尽的文档谢谢。

**Comment by vifird** [comment]
使用的Keeper是目前最新版V2.1.7吗？

**Comment by itxuye** [comment]
之前的是2.1.6，刚升级到2.1.7也是同样的问题

**Comment by itxuye** [comment]
`const loadWelcomme = (cb) => {
  import(/* webpackChunkName: "welcome" */'../container/WelcomPage/WelcomePage').then((welcome) => {
    cb(welcome)
  })
}`
我webpack升级到了3，这样的代码连chunk都没生成，但是用react-router可以的。。

**Comment by itxuye** [comment]
![wechatimg17](https://user-images.githubusercontent.com/9589686/32488957-0de2b3e0-c374-11e7-98b5-288e9b76a7f3.jpeg)
下午这样写没有报错了可以进路由了，但是代码分割和动态加载都没有生成，webpack chunkFilename是设置过的。

**Comment by itxuye** [comment]
成功了，总结下几个坑，
1.ES6模块的，需要加上module.default
2. 生成chunkfile不成功是因为在上面还有静态导入。
3.使用webpack3 可以直接用magic comment 生成chunkfile的名字

**Comment by TonyTong520** [comment]
react + webpack v3 + react-keeper
我参照文档使用react-keeper的时候也出现了同样的问题，
解决方案:
第一步： 安装 react-loadable
`npm i -S react-loadable` 以后，我们就能愉快得做dynamic import了。
第二步： 
路由配置文件里：
![image](https://user-images.githubusercontent.com/29602967/52620960-0650f900-2ee1-11e9-83c4-68cac1d4b4f3.png)
（注意： 我做完这一步：报Warning: React.createElement: type is invalid — expected a string...开头的错， 把页面文件里的export 改成export default就ok了
![image](https://user-images.githubusercontent.com/29602967/52621227-b32b7600-2ee1-11e9-9274-e000162fe869.png)
以上是我解决使用react-keeper后动态加载代码的方案，仅供参考，其他参考资料：https://segmentfault.com/a/1190000011128817
