### ISSUE TITLE
npm start出错了

### ISSUE THREAD

**Issue by Xavier0818** [vifird/react-keeper#47]
`ERROR in ./example/main/App.js
Module not found: Error: Cannot resolve module 'react-keeper' in C:\Users\tang\D                                                                                                                                                             esktop\react-keeper\example\main
 @ ./example/main/App.js 15:19-42
`
npm install也安装了，就是运行不起来

**Comment by vifird** [comment]
先执行以下`npm i react-keeper`试试。

**Comment by Xavier0818** [comment]
谢谢，问题解决了！是文件夹名字要和react-keeper不一样，要在package.json中的name中改一下就可以了，以前还真的是从来没遇到过这个问题。

**Comment by Xavier0818** [comment]
谢谢，问题解决了！是文件夹名字要和react-keeper不一样，要在package.json中的name中改一下就可以了，以前还真的是从来没遇到过这个问题。

**Comment by Xavier0818** [comment]
谢谢，问题解决了！是文件夹名字要和react-keeper不一样，要在package.json中的name中改一下就可以了，以前还真的是从来没遇到过这个问题。
