### ISSUE TITLE
CacheLink和Link不支持state吗？

### ISSUE THREAD

**Issue by laden666666** [vifird/react-keeper#5]
rt

**Comment by vifird** [comment]
`CacheLink`和`Link`本身也是React组件，所以支持State和Props，平常使用更多的应该是Props，比如自定义`className`等，这些Link组件是支持的。

**Comment by vifird** [comment]
@laden666666[ Keeper V2.0](https://github.com/vifird/react-keeper/blob/master/docs/Version.md)上线，Link 和CacheLink已经支持设置state，并可以使用Control.state读取。
