### ISSUE TITLE
关于文档

### ISSUE THREAD

**Issue by chenghy** [vifird/react-keeper#56]
想要学习react-keeper，不知道有没有详细点的api手册

**Comment by vifird** [comment]
Keeper文档本身比较简单，可以参考这里英文文档：[Keeper Docs](https://github.com/vifird/react-keeper/tree/master/docs)。如果需要中文帮助，可以看这几篇文章，写得是Keeper技术的关键点：
[React如何优雅地写单页面应用](https://zhuanlan.zhihu.com/p/26308250)，[干货 React-Keeper ](https://zhuanlan.zhihu.com/p/25081540)。
