### ISSUE TITLE
路由匹配错误bug

### ISSUE THREAD

**Issue by qfgyd2004** [vifird/react-keeper#57]
我的框架页面路由是/，登录页面路由是/login
问题是现在访问登录页面，实际匹配到的页面是框架页面。
匹配规则会优先匹配/,匹配到了就返回了，请问怎么处理？

**Comment by qfgyd2004** [comment]
我的框架页面路由是/，登录页面路由是/login
问题是现在访问登录页面，实际匹配到的页面是框架页面。
匹配规则会优先匹配/,匹配到了就返回了

**Comment by vifird** [comment]
可以参考之前的issue: #28
