### ISSUE TITLE
这个代码竟然无法定向到登录页面，请问是什么原因导致的？

### ISSUE THREAD

**Issue by qfgyd2004** [vifird/react-keeper#59]
这个代码我访问login，永远都会返回/的组件内容
`<HashRouter>
            <div>
              <Route component={ component1 } path="/">
              </Route>
              <Route component={ component2 } path="/login"/>
            </div>
          </HashRouter>`

**Comment by vifird** [comment]
参考这里的文档：[RouteMapping](https://github.com/vifird/react-keeper/blob/master/docs/RouteMapping.md)

**Comment by qfgyd2004** [comment]
按文档怎么配置都不能实现我的需求 @vifird

**Comment by vifird** [comment]
@qfgyd2004 ```<Route component={ component1 } path="/>">```
