### ISSUE TITLE
跳转路由时报错

### ISSUE THREAD

**Issue by chenghy** [vifird/react-keeper#61]
![image](https://user-images.githubusercontent.com/11433633/35138567-32c0e534-fd2a-11e7-961a-e05f49cd19cb.png)

**Comment by chenghy** [comment]
发一下我的代码，
1.路由定义
![image](https://user-images.githubusercontent.com/11433633/35139018-31efda64-fd2c-11e7-8831-656af8b4dc56.png)
2.路由跳转代码
![image](https://user-images.githubusercontent.com/11433633/35139058-5b5781ea-fd2c-11e7-9f00-c75995229ba0.png)
3.CommentPage组件定义
![image](https://user-images.githubusercontent.com/11433633/35139094-8e2717f2-fd2c-11e7-84fc-6c8ffcc05884.png)

**Comment by chenghy** [comment]
代码：
1.路由定义
![image](https://user-images.githubusercontent.com/11433633/35139658-120eb8fc-fd2f-11e7-8d4d-8698cc8bf56b.png)
2.CommentPage组件定义
![image](https://user-images.githubusercontent.com/11433633/35139680-2c44c0d6-fd2f-11e7-9590-665548653bdd.png)
3. js跳转写法
![image](https://user-images.githubusercontent.com/11433633/35139712-49d93f78-fd2f-11e7-8ee6-c52501ad7c6d.png)

**Comment by chenghy** [comment]
试了几次，发现了一个奇怪的现象。当我CommentPage 组件render方法里面返回如果不是dom元素就会报错，比如返回空字符串，纯字符串。相反如果“return <div>评论页面</div>“这种dom元素的话，就不会出错。希望能给修复下这个bug

**Comment by vifird** [comment]
React的render函数里是需要返回一个Tag或者Component的，不能直接返回字符串：[ReactJS](https://reactjs.org/docs/introducing-jsx.html)
