### ISSUE TITLE
关于activeClassName的匹配问题

### ISSUE THREAD

**Issue by Gesangs** [vifird/react-keeper#65]
在单页应用中
当给Link组件 “/index/a” 和 “/index/a/b” 都设置了 activeClassName 时，
从 “/index/a” 进入 “/index/a/b”后 ，“/index/a” 的 activeClassName 样式就失效了。
该如何解决这个问题？

**Comment by vifird** [comment]
@Gesangs 默认为全等，非全等匹配可以在组件里自实现isActive函数：[Link](https://github.com/vifird/react-keeper/blob/master/docs/Link.md)
