### ISSUE TITLE
使用cache的页面跳转问题

### ISSUE THREAD

**Issue by koupeng** [vifird/react-keeper#70]
![image](https://user-images.githubusercontent.com/6110684/38064028-a8ac6856-332e-11e8-80ad-2c7425b0a1c2.png)

**Comment by koupeng** [comment]
**一、home界面有TabBar。**
1、home下的页面，我作为一级页面
2、下面的三个作为二级页面
3、使用Control.go从一级页面跳转到二级页面
**二、问题**
1、由于/residentservices我设置了cache，只要渲染过这个cache页面，我在其他的一级页面，如/mypage跳转到二级页面时，，，仍然会存在TabBar!!!!

**Comment by koupeng** [comment]
1、发现Home下有子组件使用了cache之后，跳转到与HOME平级的页面，HOME并没有unmount.....导致HOME中的tabbar仍然存在。
2、目前，采用emitter.emit("tabBarShow",false)。给HOME页面发事件通知的方式关闭Tabbar....

**Comment by vifird** [comment]
@koupeng Home下的子组件，设置cache='parent'，默认cache模式为'root' [PageCache](https://github.com/vifird/react-keeper/blob/master/docs/PageCache.md)
