### ISSUE TITLE
页面之间传值问题

### ISSUE THREAD

**Issue by shanjie001** [vifird/react-keeper#72]
比如 两个页面 /home /picker 
1.在 /home 页面点开/picker
2.在 /picker 进行一些操作，比如选中了某些元素
3.返回 /home 页， 怎么将/picker里选择的元素传递给/home ？
目前使用 Control.go("/home", {state}) 可以将值传回，但是刷新/home页面后state依然存在，本应该被重置。
请问还有什么页面间互相传值的方式？

**Comment by vifird** [comment]
state刷新后仍然保留，是history state的特性。你的应用场景，应该是要临时存储变量，这个时候可以用跨组件通讯的方法解决，比如状态管理框架（Redux、Mobx）、React context、props等。

**Comment by shanjie001** [comment]
谢谢 @vifird  我去试试
