### ISSUE TITLE
CacheLink ios不兼容

### ISSUE THREAD

**Issue by cjmafei** [vifird/react-keeper#74]
在使用cachelink时发现，A页面跳到B页面，然后返回，在安卓机是正常的，保留了滚动条的位置，也没有刷新数据，但是ios上没有保留滚动条位置，返回顶部了

**Comment by vifird** [comment]
@cjmafei 有使用滚动插件没有？

**Comment by cjmafei** [comment]
没有使用滚动插件，安卓没问题，只出现在ios，我的系统版本是最新的

**Comment by cjmafei** [comment]
@vifird

**Comment by vifird** [comment]
@cjmafei 两个页面是单独滚动的，还是统一在body下滚动？

**Comment by cjmafei** [comment]
@vifird 在同一个body下面

**Comment by vifird** [comment]
@cjmafei 两个页面共用一个滚动容器是不太合理的，尝试让body禁止滚动，每个页面的顶部容器允许滚动。
