### ISSUE TITLE
报错：Element ref was specified as a string

### ISSUE THREAD

**Issue by webgameone** [vifird/react-keeper#79]
可以出一个react16的demo吗，按照你例子写的好像搞不定
报错：
Uncaught Error: Element ref was specified as a string (component) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded

**Comment by webgameone** [comment]
我在react16的index.js里面这样写
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import registerServiceWorker from './registerServiceWorker';
import { HashRouter, BrowserRouter, MemoryRouter, Route, Control } from 'react-keeper'

import Home from './page/home'

const App = ()=> {
    return (
      <HashRouter basename='/main'>
        <div>
          <Route miss cache component={Home} path='/' />
        </div>
      </HashRouter>
    )
}

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();

**Comment by webgameone** [comment]
你们的这个插件是不是不支持react16的最新版本?

**Comment by webgameone** [comment]
我发现了  好像是不能用cnmp安装你这个插件的样子

**Comment by webgameone** [comment]
果然是不能使用cnpm install你这个插件呢   用npm install安装就正常了

**Comment by vifird** [comment]
@webgameone 好的，非常感谢。我把这条加到文档里。

**Comment by vifird** [comment]
@webgameone 已加：[README.md](https://github.com/vifird/react-keeper/blob/master/README.md)
