### ISSUE TITLE
没找到leaveHook或者类似的相关react-router的用法

### ISSUE THREAD

**Issue by itxuye** [vifird/react-keeper#8]
切换使用了一个月了，没有啥问题，今天想找到一个类似router leave的钩子，还有Link这种携带参数，react-router有param可以配置多个，不知道这个怎么配置多个，我现在是组合String 传或者Control跳转携带Object的。
谢谢。麻烦了。

**Comment by vifird** [comment]
react-router中的钩子，在Keeper中雷同的用法是[Filter](https://github.com/vifird/react-keeper/blob/master/docs/Filter.md)。关于Link携带参数，下一个小版本会有支持，我们正在做这方面的开发。

**Comment by itxuye** [comment]
@vifird 好的谢谢，关于filter是我没看源码

**Comment by itxuye** [comment]
@vifird 有个疑惑，想知道cache的页面具体怎么在后面的过程中不cache呢？比如我注销了重新进入了配置cache的主页。但是仍然是原来的cache的，我想进入不cache的，怎么做？在Link或者Control跳转的时候是否可以加入配置是否跳到新的还是cache的。 或者在api中我没注意到。

**Comment by vifird** [comment]
@itxuye 现在Keeper对cache切换支持得还不好，我们也在做这方面的开发。之后会支持的cache切换方式是这样：
```
<Route cache={ this.state.homeCache } path='/home' component={ Home }/>
```
缓存时，可以将this.state.homeCache置为true, 'parent', 'root'， 不缓存时，可以置为false.
这个功能还在开发中，会在近期上线。

BTW： [Keeper V2.0](https://github.com/vifird/react-keeper/blob/master/docs/Version.md)今天上线了，对state做了更好的支持。

**Comment by itxuye** [comment]
想请问下这个bug,我做了简单的demo没法复现，但是在我的项目中，存在闭环的跳转，A-B-A-B，出现下面的错误
<img width="800" alt="wx20170521-174226 2x" src="https://cloud.githubusercontent.com/assets/9589686/26282885/31c70f6a-3e4d-11e7-8170-8424113f61ec.png">

**Comment by vifird** [comment]
@itxuye 可否提供一下项目代码？

**Comment by itxuye** [comment]
@vifird 真的很抱歉，我写了一个A-B-A-B这样的小demo，没有复现，可能跟公司代码有关系。所以我能通过gmail联系你加下其他的联系方式吗？

**Comment by vifird** [comment]
@itxuye 可以。邮件发我你的WeChat或者QQ吧。

**Comment by itxuye** [comment]
@vifird 前面的问题我发你邮件了，我现在暂时用的sessionStorage规避的。
另外2.0 hashrouter是支持state的，我刚刚测完Control.replace()是无法得到Control.state的,go()可以

**Comment by itxuye** [comment]
@vifird 看了文档是(has no affect in hashrouter),但是我go(‘’,{})为啥是可以读到的。
