### ISSUE TITLE
可以添加类似react-router Switch的组件吗?

### ISSUE THREAD

**Issue by tuliprope** [vifird/react-keeper#83]
可以添加类似react-router Switch的组件吗?比如：
`
    <Route path="/say/:someMsg".../>
    <Route path='/hello' .../>
`
当path='/say/hello'时两个Route都会渲染.这个该怎么办？

**Comment by vifird** [comment]
能贴一下完整路由代码吗？`/say/hello`不应该渲染`<Route path='/hello' >`

**Comment by LastStranger** [comment]
![image](https://user-images.githubusercontent.com/29811304/43686191-4807962a-98f4-11e8-8f29-bb4ff79ce084.png)
如果把"/parent"换成"/"的话，切换路由会导致Parent组件和child组件同时出现在屏幕上，有没有switch类似的东西，exact也没有效果，

**Comment by vifird** [comment]
@LastStranger 这样配置: `path='/>'`。`>`标识结束，这样只会匹配`/`，不会匹配`/parent`。文档在这里：[RouteMapping](https://github.com/vifird/react-keeper/blob/master/docs/RouteMapping.md)。

**Comment by flymzero** [comment]
为什么我有两个path， 一个设置 path='/>' 是对应首页， 另一个是path='/' 是404页, 无论怎么访问都是两个渲染在同一个页面

**Comment by flymzero** [comment]
接上面，其实是一个很简单的需求，直接输入域名访问首页，输入域名+其他东西在不匹配的情况下，跳转到404页，我实践下来，直接输入域名，会匹配首页组件，但是也会匹配404页，都是两个渲染在同一个页面

**Comment by vifird** [comment]
@flymzero 404页面的配置可以使用`miss`组件。Keeper采用可扩展路由的配置方式，允许多个匹配，这里`path='/>'`和`path='/'`都满足匹配`/`，所以会都配置，解决的方式，在404组件的路由上去掉`path`，添加`miss`就可以了。文档地址：https://github.com/vifird/react-keeper
