### ISSUE TITLE
你好，微信分享和支付的问题希望您能帮我看下

### ISSUE THREAD

**Issue by webgameone** [vifird/react-keeper#85]
我发现微信分享的路径和支付的路径一定要是www.xxx.com/?#/xxxx这样的格式才能很好的分享出去，但是现在hash默认的格式是www.xxx.com/#/xxxx   ，能不能从源码的角度将#修改成?#呢

**Comment by vifird** [comment]
这个`?`不是路由器添加的，微信配置地址的时候，在url后加`?`就可以了。
