### ISSUE TITLE
缓存是否可以隐藏在页面的dom结构

### ISSUE THREAD

**Issue by qfgyd2004** [vifird/react-keeper#89]
发现所有缓存的页面都在root节点下挂载了，通过控制display来切换页面，这是我用的不对，还是本身设计就是这样的？或者有其他优化空间吗？

**Comment by vifird** [comment]
@qfgyd2004 本身设计就是这样的，display方式是唯一能保留所有状态的方式。这样会增加内存占用，但是不会影响渲染性能；不过所有的缓存方式，都会增加内存占用。

**Comment by qfgyd2004** [comment]
@vifird  了解了，谢谢
